export default {
	login: "alfgow",
	id: 64243346,
	node_id: "MDQ6VXNlcjY0MjQzMzQ2",
	avatar_url: "https://avatars.githubusercontent.com/u/64243346?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/alfgow",
	html_url: "https://github.com/alfgow",
	followers_url: "https://api.github.com/users/alfgow/followers",
	following_url:
		"https://api.github.com/users/alfgow/following{/other_user}",
	gists_url: "https://api.github.com/users/alfgow/gists{/gist_id}",
	starred_url:
		"https://api.github.com/users/alfgow/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/alfgow/subscriptions",
	organizations_url: "https://api.github.com/users/alfgow/orgs",
	repos_url: "https://api.github.com/users/alfgow/repos",
	events_url: "https://api.github.com/users/alfgow/events{/privacy}",
	received_events_url:
		"https://api.github.com/users/alfgow/received_events",
	type: "User",
	site_admin: false,
	name: "alfgow",
	company: null,
	blog: "https://leonidasesteban.com/estudiante/alfgow",
	location: "CDMX",
	email: null,
	hireable: null,
	bio: "😎 Ola ke aze",
	twitter_username: "alfgow",
	public_repos: 30,
	public_gists: 0,
	followers: 0,
	following: 3,
	created_at: "2020-04-24T04:37:01Z",
	updated_at: "2022-09-15T11:57:43Z",
};
